// background_images.cpp
// NDS background data
// This file was automatically generated by Spritely 

#include "background_images.h"


// Info for each background map:
const BgImageInfoStruct BgImageInfo[] = {
};
