// main.cpp
// Sample NDS project to demonstrate how to display sprites/backgrounds.
// This file was automatically generated by Spritely 

#include <nds.h>

#include "game_state.h"
#include "object_utils.h"

void InitDevice() {
	powerOn(POWER_ALL_2D);
	
	// Enable interrupts.
	irqInit();
	irqEnable(IRQ_VBLANK);
}

int main() {
	InitDevice();

	// Initialize the Objects.
	// This initializes all the objects to "off" so that we don't have garbage
	// appearing on the screen.
	InitializeObjects();

	GameState gs;
	UpdateScreen();

	while (true) {
		// Wait for the vertical blank interrupt so that we update the
		// screen at a constant rate.
		swiWaitForVBlank();

		gs.Update();
		UpdateScreen();
	}
}
